# Generated by Django 5.2.1 on 2025-05-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitems',
            name='item_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
