# Generated by Django 5.2.1 on 2025-05-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_marketitems_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketitems',
            name='location',
        ),
    ]
