# Generated by Django 5.2.1 on 2025-05-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_marketitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketitems',
            name='items_name',
            field=models.CharField(max_length=1000),
        ),
    ]
