# Generated by Django 5.2.1 on 2025-05-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_marketitems_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='weight',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
