# Generated by Django 5.2.1 on 2025-05-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_marketitems_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketitems',
            name='item_rating',
            field=models.IntegerField(default=0),
        ),
    ]
