# Generated by Django 5.2.1 on 2025-05-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cart_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='weight',
        ),
        migrations.AddField(
            model_name='marketitems',
            name='min_weight',
            field=models.IntegerField(default=0),
        ),
    ]
