# Generated by Django 5.2.1 on 2025-05-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_cart_weight_marketitems_min_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='phone_number',
            field=models.PositiveIntegerField(default=7759059001, max_length=10),
        ),
    ]
