# Generated by Django 5.2.1 on 2025-05-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_marketitems_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitems',
            name='location',
            field=models.CharField(default='Neelbad, Bhopal, Mp', max_length=300),
        ),
    ]
