# Generated by Django 5.2.1 on 2025-05-31 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_marketitems_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=1000)),
                ('items_description', models.TextField(max_length=1000)),
                ('item_price', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='market_items/')),
                ('items_weight', models.IntegerField()),
                ('item_rating', models.IntegerField(default=0)),
                ('location', models.CharField(default='Neelbad, Bhopal, Mp', max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
