# Generated by Django 5.2.1 on 2025-06-14 04:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_marketitems_item_list_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerhistory',
            name='item_list_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
