# Generated by Django 5.2.1 on 2025-07-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_farmerhistory_item_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerhistory',
            name='item_list_date',
            field=models.DateTimeField(),
        ),
    ]
